### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
1.  Fetch and merge upstream
2.  Added failing test for #2482
3.  Fixed two test failures that were present in your PR

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
re https://github.com/pymc-devs/pymc3/pull/2468

**Comment by kyleabeauchamp** [comment]
There are still ~3 failures that you need to fix in your PR after merging this, they all seem to be cases where the starting point for the MLE has a non-finite logP.

**Comment by kyleabeauchamp** [comment]
Probably due to bad starting points or something.

**Comment by aseyboldt** [comment]
Maybe just wait with this until #2482 is merged. We can then cherry-pick the commits with the tests and add them to #2499 after that has been rebased.

**Comment by bwengals** [comment]
wow cool, thanks for doing this!!

**Pull request merged**
